enum AppointmentStatus {
    PENDING @enum(value: "pending")
    COMPLETED @enum(value: "completed")
}

type Appointment {
    id: ID!
    patient_name: String!
    patient_phone: String!
    patient_email: String
    doctor_name: String
    service_name: String!
    appointment_date: String!
    appointment_time: String!
    status: AppointmentStatus!
}

extend type Query {
    appointments: [Appointment!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\AppointmentResolver@show")
}

extend type Mutation {
    createAppointment(
        patient_name: String!
        patient_phone: String!
        patient_email: String
        doctor_name: String
        service_name: String!
        appointment_date: String!
        appointment_time: String!
        status: AppointmentStatus
    ): Appointment
        @field(resolver: "App\\GraphQL\\Resolvers\\AppointmentResolver@create")
        @guard(with: ["sanctum"])

    deleteAppointment(id: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\AppointmentResolver@destroy")
        @guard(with: ["sanctum"])
}
