# نوع الـ Appointment
type Appointment {
    id: ID!
    patient_name: String!
    patient_phone: String!
    patient_email: String
    doctor_name: String
    service_name: String!
    appointment_date: String!
    appointment_time: String!
    status: String
}

# Input Object لـ Create / Update
input AppointmentInput {
    patient_name: String!
    patient_phone: String!
    patient_email: String
    doctor_name: String
    service_name: String!
    appointment_date: String!
    appointment_time: String!
    status: String
}

# Queries
extend type Query {
    appointments: [Appointment!]!
        @field(
            resolver: "App\\Modules\\Appointment\\GraphQL\\AppointmentResolver@list"
        )
    appointment(id: ID!): Appointment
        @field(
            resolver: "App\\Modules\\Appointment\\GraphQL\\AppointmentResolver@show"
        )
}

# Mutations
extend type Mutation {
    createAppointment(input: AppointmentInput!): Appointment
        @field(
            resolver: "App\\Modules\\Appointment\\GraphQL\\AppointmentResolver@create"
        )

    updateAppointment(id: ID!, input: AppointmentInput!): Appointment
        @field(
            resolver: "App\\Modules\\Appointment\\GraphQL\\AppointmentResolver@update"
        )

    deleteAppointment(id: ID!): Boolean
        @field(
            resolver: "App\\Modules\\Appointment\\GraphQL\\AppointmentResolver@delete"
        )
}
