type User {
    id: ID!
    tenant_id: String! # لو حابب ترجع الـ tenant
    name: String!
    email: String!
    phone: String
    profile_image: String
}

input RegisterInput {
    name: String!
    email: String! @rules(apply: ["email"])
    phone: String
    password: String!
    password_confirmation: String!
}

input LoginInput {
    email: String!
    password: String!
}

input ResetPasswordInput {
    email: String! @rules(apply: ["email"])
    code: String!
    password: String! @rules(apply: ["confirmed", "min:6"])
    password_confirmation: String!
}

type AuthPayload {
    status: Boolean!
    message: String!
    user: User
    token: String
}

type LogoutPayload {
    status: Boolean!
    message: String!
}

extend type Mutation {
    register(input: RegisterInput!): AuthPayload
        @field(resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@register")
    login(input: LoginInput!): AuthPayload
        @field(resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@login")
    logout: LogoutPayload
        @field(resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@logout")

    forgotPassword(email: String! @rules(apply: ["email"])): AuthPayload
        @field(
            resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@forgotPassword"
        )

    resetPassword(input: ResetPasswordInput!): AuthPayload
        @field(
            resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@resetPassword"
        )
}

extend type Query {
    me: AuthPayload
        @field(resolver: "App\\Modules\\User\\GraphQL\\AuthResolver@me")
}
