type User {
    id: ID!
    tenant_id: String! # لو حابب ترجع الـ tenant
    name: String!
    email: String!
    phone: String
    profile_image: String
}

input RegisterInput {
    name: String!
    email: String!
    phone: String!
    password: String!
    password_confirmation: String!
}

input LoginInput {
    email: String!
    password: String!
}

type AuthPayload {
    status: Boolean!
    message: String!
    user: User
    token: String
}

type LogoutPayload {
    status: Boolean!
    message: String!
}

input ForgotPasswordInput {
    email: String! # بدل identifier
}

input VerifyOtpInput {
    email: String! # بدل identifier
    code: String!
}

input ResetPasswordInput {
    token: String!
    password: String!
    password_confirmation: String!
}

input ResendOtpInput {
    email: String! # بدل identifier
}

type VerificationPayload {
    status: Boolean!
    message: String!
    token: String # Token for resetting password
}

extend type Mutation {
    register(input: RegisterInput!): AuthPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@register")
    login(input: LoginInput!): AuthPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@login")
    logout: LogoutPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@logout")

    forgotPassword(input: ForgotPasswordInput!): VerificationPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@forgotPassword")
    verifyOtp(input: VerifyOtpInput!): VerificationPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@verifyOtp")
    resetPassword(input: ResetPasswordInput!): VerificationPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@resetPassword")
    resendOtp(input: ResendOtpInput!): VerificationPayload
        @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@resendOtp")
}

extend type Query {
    me: AuthPayload @field(resolver: "App\\GraphQL\\Resolvers\\AuthResolver@me")
}
