type ClinicSectionItem {
    id: ID!
    title: String
    description: String
    value: String
    order: Int
    is_active: Boolean
}

type ClinicSection {
    id: ID!
    key: String!
    title: String
    is_active: Boolean
    items: ClinicSectionItem
}

extend type Query {
    clinicSections: [ClinicSection!]!
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicSectionResolver@list"
        )
    showClinicSection(id: ID!): ClinicSection
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicSectionResolver@show"
        )
}

extend type Mutation {
    createClinicSection(
        key: String!
        title: String
        is_active: Boolean
        items: ClinicSectionItemInput
    ): ClinicSection
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicSectionResolver@create"
        )

    updateClinicSection(
        id: ID!
        key: String
        title: String
        is_active: Boolean
        items: ClinicSectionItemInput
    ): ClinicSection
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicSectionResolver@update"
        )

    deleteClinicSection(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicSectionResolver@delete"
        )
}

input ClinicSectionItemInput {
    title: String
    description: String
    value: String
    order: Int
    is_active: Boolean
}


