type Clinic {
    id: ID!
    name: String!
    logo: String
    color: String
}

extend type Query {
    # جلب عيادة المستخدم الحالي
    clinic: Clinic
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@show")
}

extend type Mutation {
    # تحديث عيادة المستخدم الحالي
    updateClinic(name: String, color: String, logo: Upload): Clinic
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@update")

    # حذف عيادة المستخدم الحالي
    deleteClinic: Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@destroy")
}
