type ClinicSchedule {
    id: ID!
    clinic_id: ID!
    date_from: String
    date_to: String
    time_from: String
    time_to: String
}

extend type Query {
    clinicSchedules: [ClinicSchedule!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicScheduleResolver@show")
}

extend type Mutation {
    createOrUpdateClinicSchedule(
        id: ID
        date_from: String
        date_to: String
        time_from: String
        time_to: String
    ): ClinicSchedule
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicScheduleResolver@createOrUpdate"
        )

    deleteClinicSchedule(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicScheduleResolver@destroy"
        )
}
