type Clinic {
    id: ID!
    name: String!
    logo: String
    color: String
    is_active: Boolean!
}

extend type Query {
    # جلب كل العيادات
    clinics: [Clinic!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@list")

    # جلب عيادة محددة
    clinic(id: ID!): Clinic
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@show")
}

extend type Mutation {
    # إنشاء عيادة
    createClinic(
        name: String!
        color: String
        is_active: Boolean
        logo: Upload
    ): Clinic
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@create")

    # تحديث عيادة
    updateClinic(
        id: ID!
        name: String
        color: String
        is_active: Boolean
        logo: Upload
    ): Clinic
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@update")

    # حذف عيادة
    deleteClinic(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicResolver@destroy"
        )
}


