# نوع البيانات اللي هيتخزن في DB
type ClinicStatistic {
    id: ID!
    clinic_id: ID!
    items: JSON
}

# Query عشان تجيب بيانات الإحصائيات
extend type Query {
    clinicStatistics: ClinicStatistic
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicStatisticResolver@show"
        )
}

# Input Type عشان كل عنصر في Array
input ClinicStatisticItemInput {
    statisitics_name: String!
    statisitics_no: String!
}

# Mutations لإنشاء/تحديث أو حذف الإحصائيات
extend type Mutation {
    # إنشاء أو تحديث الإحصائيات
    createOrUpdateClinicStatistics(
        items: [ClinicStatisticItemInput!]!
    ): ClinicStatistic
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicStatisticResolver@createOrUpdate"
        )
        @guard(with: ["sanctum"])

    # حذف كل إحصائيات العيادة
    deleteClinicStatistics: Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicStatisticResolver@destroy"
        )
        @guard(with: ["sanctum"])
}
