type ClinicNews {
    id: ID!
    clinic_id: ID!
    title: String!
    content: JSON
    image: String
}

extend type Query {
    clinicNews: [ClinicNews!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicNewsResolver@show")
}

extend type Mutation {
    createOrUpdateClinicNews(
        id: ID
        title: String!
        content: JSON
        image: Upload
    ): ClinicNews
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ClinicNewsResolver@createOrUpdate"
        )
        @guard(with: ["sanctum"])

    deleteClinicNews(id: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\ClinicNewsResolver@destroy")
        @guard(with: ["sanctum"])
}
