type CompanyPaymentPlan {
    id: ID!
    insurance_company_id: ID!
    is_active: Boolean!
}

extend type Query {
    companyPaymentPlans: [CompanyPaymentPlan!]!
        @field(
            resolver: "App\\GraphQL\\Resolvers\\CompanyPaymentPlanResolver@list"
        )

    companyPaymentPlan(id: ID!): CompanyPaymentPlan
        @field(
            resolver: "App\\GraphQL\\Resolvers\\CompanyPaymentPlanResolver@show"
        )
}

extend type Mutation {
    createCompanyPaymentPlan(
        insurance_company_id: ID!
        is_active: Boolean
    ): CompanyPaymentPlan
        @field(
            resolver: "App\\GraphQL\\Resolvers\\CompanyPaymentPlanResolver@create"
        )

    updateCompanyPaymentPlan(
        id: ID!
        insurance_company_id: ID
        is_active: Boolean
    ): CompanyPaymentPlan
        @field(
            resolver: "App\\GraphQL\\Resolvers\\CompanyPaymentPlanResolver@update"
        )

    deleteCompanyPaymentPlan(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\CompanyPaymentPlanResolver@destroy"
        )
}


