type CompanyPaymentPlan {
    id: ID!
    insurance_company_id: ID!
    is_active: Boolean!
}

extend type Query {
    companyPaymentPlans: [CompanyPaymentPlan!]!
        @field(resolver: "App\\Modules\\CompanyPaymentPlan\\GraphQL\\CompanyPaymentPlanResolver@list")

    companyPaymentPlan(id: ID!): CompanyPaymentPlan
        @field(resolver: "App\\Modules\\CompanyPaymentPlan\\GraphQL\\CompanyPaymentPlanResolver@show")
}

extend type Mutation {
    createCompanyPaymentPlan(
        insurance_company_id: ID!
        is_active: Boolean
    ): CompanyPaymentPlan
        @field(resolver: "App\\Modules\\CompanyPaymentPlan\\GraphQL\\CompanyPaymentPlanResolver@create")

    updateCompanyPaymentPlan(
        id: ID!
        insurance_company_id: ID
        is_active: Boolean
    ): CompanyPaymentPlan
        @field(resolver: "App\\Modules\\CompanyPaymentPlan\\GraphQL\\CompanyPaymentPlanResolver@update")

    deleteCompanyPaymentPlan(id: ID!): Boolean
        @field(resolver: "App\\Modules\\CompanyPaymentPlan\\GraphQL\\CompanyPaymentPlanResolver@destroy")
}
