type ContactMessage {
    id: ID!
    name: String!
    email: String
    phone: String
    subject: String
    message: String!
}

extend type Query {
    contactMessages: [ContactMessage!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@list")

    contactMessage(id: ID!): ContactMessage
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@show")
}

extend type Mutation {
    createContactMessage(
        name: String!
        email: String
        phone: String
        subject: String
        message: String!
    ): ContactMessage
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@create")

    updateContactMessage(
        id: ID!
        name: String
        email: String
        phone: String
        subject: String
        message: String
    ): ContactMessage
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@update")

    deleteContactMessage(
        id: ID!
    ): Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@destroy")
}


