type ContactMessage {
    id: ID!
    name: String!
    email: String
    phone: String
    subject: String
    message: String!
}

extend type Query {
    contactMessages: [ContactMessage!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@list")
        @guard(with: ["sanctum"])

    contactMessage: ContactMessage
        @field(resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@show")
        @guard(with: ["sanctum"])
}

extend type Mutation {
    createContactMessage(
        name: String!
        email: String
        phone: String
        subject: String
        message: String!
    ): ContactMessage
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@create"
        )

    updateContactMessage(
        id: ID!
        name: String
        email: String
        phone: String
        subject: String
        message: String
    ): ContactMessage
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@update"
        )
        @guard(with: ["sanctum"])

    deleteContactMessage(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\ContactMessageResolver@destroy"
        )
        @guard(with: ["sanctum"])
}
