type DoctorDepartment {
    id: ID!
    name: String!
    content: String
}

type Doctor {
    id: ID!
    clinic_id: ID!
    name: String!
    specialization: String!
    experience: String!
    image: String
    departments: [DoctorDepartment!] @hasMany
}

input DoctorDepartmentInput {
    name: String!
    content: String
}

extend type Query {
    doctors: [Doctor!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@show")
}

extend type Mutation {
    createOrUpdateDoctor(
        id: ID
        name: String!
        specialization: String!
        experience: String!
        image: Upload
        departments: [DoctorDepartmentInput!]
    ): Doctor
        @field(
            resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@createOrUpdate"
        )

    deleteDoctor(id: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@destroy")
}
