type Doctor {
    id: ID!
    doctor_data: JSON!
    is_active: Boolean!
}

extend type Query {
    doctors: [Doctor!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@list")

    doctor(id: ID!): Doctor
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@show")
}

extend type Mutation {
    createDoctor(doctor_data: JSON!, is_active: Boolean, image: Upload): Doctor
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@create")

    updateDoctor(
        id: ID!
        doctor_data: JSON
        is_active: Boolean
        image: Upload
    ): Doctor
        @field(resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@update")

    deleteDoctor(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\DoctorResolver@destroy"
        )
}


