type HeroSection {
    id: ID!
    clinic_id: ID!
    title: String
    sub_title: String
    content: String
    image: String
}

extend type Query {
    heroSection: HeroSection
        @field(resolver: "App\\GraphQL\\Resolvers\\HeroSectionResolver@show")
}

extend type Mutation {
    createOrUpdateHeroSection(
        title: String
        sub_title: String
        content: String
        image: Upload
    ): HeroSection
        @field(
            resolver: "App\\GraphQL\\Resolvers\\HeroSectionResolver@createOrUpdate"
        )
        @guard(with: ["sanctum"])

    deleteHeroSection: Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\HeroSectionResolver@destroy")
        @guard(with: ["sanctum"])
}
