type InsuranceCompany {
    id: ID!
    name: String!
    link: String
    image: String
}

extend type Query {
    # جلب كل شركات التأمين
    insuranceCompanies: [InsuranceCompany!]!
        @field(
            resolver: "App\\GraphQL\\Resolvers\\InsuranceCompanyResolver@list"
        )

    # جلب شركة تأمين محددة بناءً على tenant_id من التوكن
    insuranceCompany: InsuranceCompany
        @field(
            resolver: "App\\GraphQL\\Resolvers\\InsuranceCompanyResolver@show"
        )
        @guard(with: ["sanctum"])
}

extend type Mutation {
    # إنشاء شركة تأمين
    createInsuranceCompany(
        name: String!
        link: String
        image: Upload
    ): InsuranceCompany
        @field(
            resolver: "App\\GraphQL\\Resolvers\\InsuranceCompanyResolver@create"
        )
        @guard(with: ["sanctum"])

    updateInsuranceCompany(
        id: ID!
        name: String
        link: String
        image: Upload
    ): InsuranceCompany
        @field(
            resolver: "App\\GraphQL\\Resolvers\\InsuranceCompanyResolver@update"
        )
        @guard(with: ["sanctum"])

    # حذف شركة تأمين
    deleteInsuranceCompany(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\InsuranceCompanyResolver@destroy"
        )
        @guard(with: ["sanctum"])
}
