type InsuranceCompany {
    id: ID!
    name: String!
    link: String
    image: String
    is_active: Boolean!
}

extend type Query {
    # جلب كل شركات التأمين
    insuranceCompanies: [InsuranceCompany!]!
        @field(
            resolver: "App\\Modules\\InsuranceCompany\\GraphQL\\InsuranceCompanyResolver@list"
        )

    # جلب شركة تأمين محددة
    insuranceCompany(id: ID!): InsuranceCompany
        @field(
            resolver: "App\\Modules\\InsuranceCompany\\GraphQL\\InsuranceCompanyResolver@show"
        )
}

extend type Mutation {
    # إنشاء شركة تأمين
    createInsuranceCompany(
        name: String!
        link: String
        is_active: Boolean
        image: Upload
    ): InsuranceCompany
        @field(
            resolver: "App\\Modules\\InsuranceCompany\\GraphQL\\InsuranceCompanyResolver@create"
        )

    # تحديث شركة تأمين
    updateInsuranceCompany(
        id: ID!
        name: String
        link: String
        is_active: Boolean
        image: Upload
    ): InsuranceCompany
        @field(
            resolver: "App\\Modules\\InsuranceCompany\\GraphQL\\InsuranceCompanyResolver@update"
        )

    # حذف شركة تأمين
    deleteInsuranceCompany(id: ID!): Boolean
        @field(
            resolver: "App\\Modules\\InsuranceCompany\\GraphQL\\InsuranceCompanyResolver@destroy"
        )
}
