type Mission {
    id: ID!
    clinic_id: ID!
    mission: String
    image: String
}

extend type Query {
    mission: Mission
        @field(resolver: "App\\GraphQL\\Resolvers\\MissionResolver@show")
}

extend type Mutation {
    createOrUpdateMission(mission: String!, image: Upload): Mission
        @field(
            resolver: "App\\GraphQL\\Resolvers\\MissionResolver@createOrUpdate"
        )
        @guard(with: ["sanctum"])
    deleteMission: Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\MissionResolver@destroy")
        @guard(with: ["sanctum"])
}
