scalar JSON
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

"""
Root Query
"""
type Query

"""
Root Mutation
"""
type Mutation

#import doctor.graphql
#import specification.graphql
#import clinic.graphql
#import clinic_management_members.graphql
#import clinic_news.graphql
#import clinic_schedule.graphql
#import clinic_statistics.graphql
#import department.graphql
#import insurance_company.graphql
#import company_payment_plans.graphql
#import contact_message.graphql
#import unit.graphql
#import hero_sections.graphql
#import mediacenter.graphql
#import clinic_section.graphql
#import appointment.graphql
