scalar JSON @scalar(class: "App\\GraphQL\\Scalars\\Json")
scalar Upload
    @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

"""
Root Query
"""
type Query

"""
Root Mutation
"""
type Mutation

input LocalizedStringInput {
    ar: String!
    en: String!
}

#import auth_user.graphql
#import doctor.graphql
#import specification.graphql
#import clinic.graphql
#import clinic_management_members.graphql
#import clinic_news.graphql
#import clinic_schedule.graphql
#import clinic_statistics.graphql
#import department.graphql
#import insurance_company.graphql
#import contact_message.graphql
#import unit.graphql
#import hero_sections.graphql
#import mediacenter.graphql
#import appointment.graphql
#import why_us.graphql
#import about_us.graphql
#import mission.graphql
#import vision.graphql
#import social_media.graphql
#import contact_info.graphql
#import clinic_articles.graphql
#import installment_methods.graphql
