type Specification {
    id: ID!
    name: String!
    description: String
}

extend type Query {
    # جلب كل الـ Specifications
    specifications: [Specification!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\SpecificationResolver@list")

    # جلب Specification محدد
    specification(id: ID!): Specification
        @field(resolver: "App\\GraphQL\\Resolvers\\SpecificationResolver@show")
}

extend type Mutation {
    # إنشاء Specification
    createSpecification(name: String!, description: String): Specification
        @field(
            resolver: "App\\GraphQL\\Resolvers\\SpecificationResolver@create"
        )
        @guard(with: ["sanctum"])

    # تحديث Specification
    updateSpecification(
        id: ID!
        name: String
        description: String
    ): Specification
        @field(
            resolver: "App\\GraphQL\\Resolvers\\SpecificationResolver@update"
        )
        @guard(with: ["sanctum"])

    # حذف Specification
    deleteSpecification(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Resolvers\\SpecificationResolver@destroy"
        )
        @guard(with: ["sanctum"])
}
