type Unit {
    id: ID!
    name: String!
    description: String
    image: String
    is_active: Boolean!
}

extend type Query {
    units: [Unit!]!
        @field(resolver: "App\\Modules\\Unit\\GraphQL\\UnitResolver@list")
    unit(id: ID!): Unit
        @field(resolver: "App\\Modules\\Unit\\GraphQL\\UnitResolver@show")
}

extend type Mutation {
    createUnit(
        name: String!
        description: String
        image: Upload
        is_active: Boolean
    ): Unit @field(resolver: "App\\Modules\\Unit\\GraphQL\\UnitResolver@create")

    updateUnit(
        id: ID!
        name: String
        description: String
        image: Upload
        is_active: Boolean
    ): Unit @field(resolver: "App\\Modules\\Unit\\GraphQL\\UnitResolver@update")

    deleteUnit(id: ID!): Boolean
        @field(resolver: "App\\Modules\\Unit\\GraphQL\\UnitResolver@destroy")
}
