type Unit {
    id: ID!
    name: String!
    description: String
    image: String
}

extend type Query {
    units: [Unit!]!
        @field(resolver: "App\\GraphQL\\Resolvers\\UnitResolver@list")
    unit(id: ID!): Unit
        @field(resolver: "App\\GraphQL\\Resolvers\\UnitResolver@show")
}

extend type Mutation {
    createUnit(name: String!, description: String, image: Upload): Unit
        @field(resolver: "App\\GraphQL\\Resolvers\\UnitResolver@create")
        @guard(with: ["sanctum"])

    updateUnit(id: ID!, name: String, description: String, image: Upload): Unit
        @field(resolver: "App\\GraphQL\\Resolvers\\UnitResolver@update")
        @guard(with: ["sanctum"])

    deleteUnit(id: ID!): Boolean
        @field(resolver: "App\\GraphQL\\Resolvers\\UnitResolver@destroy")
        @guard(with: ["sanctum"])
}
